slogan: “宁静致远”
email: example@email.com
logo: "/images/logo.svg"

mathjax: false

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage:
  enable: false
  pages:
    - name:
      path: # 若不设置则默认使用 name
      title:
      icon: #
      description:

index:
  motto: "应无所住 而生其心"
  poem:
    - 君不见高堂明镜悲白发
    - 朝如青丝暮成雪
  photo: /images/about.jpg
  about:
    title: 关于
    text:
      - 酒入豪肠,七分酿成了月光
      -
      - 余下的三分啸成剑气
      -
      - 绣口一吐就半个盛唐

foot:
  title:
    - "海内存知己"
    - "天涯若比邻"

links:
  - name: "Theme Tranquility"
    url: https://marie0909.github.io/

social:
  - name: "github"
    icon: "/images/logo-github.svg"
    url: https://github.com/
  - name: "微信公众号"
    icon: "/images/logo-wx.svg"
    url: https://mp.weixin.qq.com/s?__biz=MzI3NzQ4NDkzNg==&mid=2247484469&idx=1&sn=8a442bb67397f52cce5c38c3f9b41e36&chksm=eb64c0d2dc1349c40d2e1bb55615ae28b3f2951be22f00717b9ade98c851082e42dc666ab45d#rd
  - name: "知乎"
    icon: "/images/logo-zh.svg"
    url: https://www.zhihu.com/

reward:
  enable: false
  face:
  paycode:
  text: “请作者喝杯咖啡”
  btnText: 喜欢作者

gitalk:
  enable: false
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>
